### PR TITLE
request for feedback on final project

### PR DESCRIPTION
**Pull request by lucypullen**
The good news is I have an api key for live ais data for 14 vessels (see vesseltracker_api).
The bad news is the map isn't working. Suggestions? 
LP

### CODE REVIEW

**Comment by lucypullen** [comment]
Hi Neil, do you have time this week to talk about this? I'd really appreciate it. Thank you. LP

**Comment by fitnr** [comment]
@lucypullen please email me and we can talk

**Comment by lucypullen** [comment]
It works! Data is on carto editor. Each point is a port. Thrilling....
Can you help me make an API for the fleet?  
LP

lucypullen@gmail.com
(347) 922-8983



[final_pullen.zip](https://github.com/fitnr/savi-750/files/959610/final_pullen.zip)

**Comment by lucypullen** [comment]
it only works if you set up a local server with terminal by typing
 python -m SimpleHTTPServer

and this address for browser to start:

http://127.0.0.1:8000

but you probably knew that!

**Pull request closed without merging**
